services:
  - type: web
    name: enterprise-risk-backend
    env: node
    repo: https://github.com/fre3thawt/enterprise-risk-tracker
    branch: main
    rootDir: backend
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: MONGODB_URI
        value: <your-mongodb-uri>
